Backend Djoser Settings
bounswe/2021SpringGroup9 pull request #365
Opened 2021-12-02 15:56 UTC by melihaydogd

Djoser settings are done. User can be created and an activation mail will be sent to the user.

2021-12-02 19:36 UTC, mertlkn commented
Can we add to settings.py:

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'BLACKLIST_AFTER_ROTATION': False,
}

because otherwise i'm getting an error on the jwt side.

2021-12-02 20:15 UTC, mertlkn approved these changes

2021-12-03 08:12 UTC, zcanfes requested changes
Other than what I commented below, everything seems fine. The email templates look very good and the code works correctly.

2021-12-03 17:13 UTC, melihaydogd commented on postory/backend/user_endpoint/models.py
>              raise ValueError('Users must have an username')
Yes, you are right. Actually, there is no need for this check. The fields will be checked on frontend.

2021-12-05 07:23 UTC, zcanfes approved these changes
Everything looks to be working fine :)

2021-12-09 16:09 UTC, merged